### PR TITLE
replace apostrophe, quote and dash with Unicode characters

### PR DESCRIPTION
**Pull request by rsperberg**
I have manually checked every change made.

### CODE REVIEW

**Comment by sethwoodworth** [comment]
PR received.  The diff isn't viewable here?  I'll do a quick visual scan of the [patch](https://github.com/GITenberg/Heart-of-Darkness_219/pull/2.patch) and accept.

**Comment by rsperberg** [comment]
That's weird. I can definitely see diffs on the shorter pull requests, but not on the first, main pull request.
I diffed the two files in Sublime Text; there are, obviously, hundreds of changes effected by the script — I guess 1,207 lines were changed, according to GitHub.

The other two pull requests are for changes that the script did not bring about, and it seemed best to separate them from the programmatic changes.

Btw, I see that the beginning of the text identifies it as ASCII and the five types of changes — left and right single quote, left and right double quote, em dash — that the script makes all substitute Unicode characters, so it should be labled UTF-8 or Unicode

**Comment by sethwoodworth** [comment]
Line [168](https://github.com/rsperberg/Heart-of-Darkness_219/blob/master/219.txt#L168)

> like. Sand-banks, marshes, forests, savages,--precious little to eat

Does your physical copy of _Heart_ have a comma followed by an em-dash?

**Comment by sethwoodworth** [comment]
At the very end of the doc:

> -"'Everything that could be done--' I mumbled.
> +“‘Everything that could be done——’ I mumbled.

Is this one of the double em-dashes you were talking about?

> -hear....'
> +hear....’

What is with all of the four period ellipses? What does your physical copy say?

**Comment by rsperberg** [comment]
Yes, this is one of the instances in which a comma is followed by a dash in the printed text. I believe there are more instances of this in the printed text than in the `219.txt` file but this is not a situation where I think they should all be restored for textual authenticity if the producers of the book happened to omit some.

Also there are sometimes three dots in an ellipsis ending a sentence and sometimes four; in "The Nigger of the Narcissus" Conrad ends one sentence with an exclamation mark followed by an ellipsis and another with an ellipsis followed by an exclamation mark. So what is normal and usual is not easy to discern. I confirmed a handful of four dots but after that I just trusted what was in the `.txt` file.

Years ago, I was taught that a 2-em dash should be used when cutting off dialog and interjecting a completely independent paragraph (and also at the beginning of the dialog when resumed). I don't see such a rule in _Chicago Manual_ now, nor find any reference to it in a quick survey online, but it's somewhat the rule that Conrad follows, at least when indicating the speaker isn't prepared to continue a thought. But when he does use 2-em dashes and when he doesn't are not consistent enough to identify a rule. There are 20 instances of 2-em dashes in the printed text of _Heart of Darkness_. 

In the `.txt` version of "The Nigger of the Narcissus," at least some of the 2-em dashes are represented by 6 hyphens (the printed text clearly shows 2-em dashes and not 3-em dashes), btw.

**Comment by sethwoodworth** [comment]
@rsperberg I'm not capable of getting a list of open PRs for GITenberg, so this PR fell off of my radar :-(  Boo on me!

Are you feeling solid on this PR? If so, I'm willing to merge.

**Pull request merged**
